schema_version: 1
name: jboss.container.wildfly.launch-config.config
version: '2.0'
description: Scripts to adjust the configuration via xml markers or CLI


envs:
    - name: "DISABLE_BOOT_SCRIPT_INVOKER"
      example: "true"
      description: "If true, then a CLI process + embedded server is used to configure the server. If not set, and no user extensions are installed, the startup CLI script is executed from the server builtin script invoker. If user extensions are installed, CLI script will be executed for user extensions."
    - name: "BOOT_SCRIPT_INVOKER_TIMEOUT"
      example: "30"
      description: "Timeout in seconds to wait for the server to be done executing builtin scripts. Default is 30 seconds"
        
execute:
- script: configure.sh
  user: '185'